FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    netcat \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install -r requirements.txt

EXPOSE 8001

CMD ["python", "-m", "uvicorn", "version_control.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]