# Generated by Django 5.2.1 on 2025-05-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_learningcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
