# Generated by Django 5.2.1 on 2025-06-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_topic_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='status',
        ),
    ]
