# Generated by Django 5.2.1 on 2025-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_remove_homework_difficulty_remove_homework_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='topics', to='tutor.student'),
        ),
    ]
