# Generated by Django 5.2.1 on 2025-06-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_homeworkresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='goals', to='tutor.learningcategory'),
        ),
    ]
