# Generated by Django 5.2.1 on 2025-06-03 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_remove_homework_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
