# Generated by Django 5.2.1 on 2025-05-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EGE', 'ЕГЭ'), ('OGE', 'ОГЭ'), ('SCHOOL', 'Школьная программа'), ('PROGRAMMING', 'Программирование')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VU', 'ВУ'), ('RU', 'РУ')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('learning_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.learningcategory')),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.learninggoal')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField()),
                ('covered_topics', models.TextField()),
                ('working_on', models.TextField()),
                ('recommended_lessons', models.IntegerField()),
                ('recommendation_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.lessontype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Задано'), ('NOT_ASSIGNED', 'Не задано')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Легкий'), ('MEDIUM', 'Средний'), ('HARD', 'Сложный')], max_length=20)),
                ('result', models.FloatField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.lesson')),
                ('topics', models.ManyToManyField(to='tutor.topic')),
            ],
        ),
    ]
