# Generated by Django 5.2.1 on 2025-05-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_learningcategory_slug_alter_homework_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcategory',
            name='slug',
        ),
    ]
